#!/bin/bash
set -e

# 1. Reload systemd to recognize the new service file
systemctl daemon-reload

# 2. Enable and start your service
systemctl enable r2_control.service
systemctl restart r2_control.service

# 3. Configure Apache
# rm /etc/apache2/sites-enabled/000-default.conf
a2ensite 000-r2.conf

# 4. Restart Apache to apply changes
systemctl restart apache2

exit 0